name: Run Jest System Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  system_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ secrets.MONGODB_VERSION }}
          mongodb-username: ${{ secrets.MONGODB_USER }}
          mongodb-password: ${{ secrets.MONGODB_PASSWORD }}

      - name: Install Dependencies
        run: npm install
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Jest System Tests
        run: npm run test:system
        env:
          MONGODB_URI: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASSWORD }}@localhost:27017/flock_watch_test?authSource=admin
          SCRAPE_URL: ${{ secrets.SCRAPE_URL }}